### ISSUE TITLE
‘acquire_removed_points()’ not collect the points deleted in the downsample process ?

### ISSUE THREAD

**Issue by Woodpecker0** [hku-mars/ikd-Tree#10]
I did some tests and read the code.  It seems that ikd-tree does not collect those points deleted in the downsample process. Can I get the missing points from "Downsample_Storage" ?

 (I really need those points, because I need to do object tracking with them.)

PCL kdtree provides index to mark origin map points and all points are managered out of kdtree,
 but ikd-tree does not have index.

Now I define an embedded index uint32_t value in "PointType" to solve this problem, but it's not perfect because it's growing and will overflow soon.

**Comment by Ecstasy-EC** [comment]
Hey @Woodpecker0 !

For the first question, yes. Please remove all the two conditions ``&& !root->point_downsample_deleted`` in the function ``flatten``. Then DIY your own conditions in the same place and store the points you need in a global storage. 

For your second question, sorry that we did not provide indices. The ``ikd-Tree`` is design to achieve high efficiency in both time and space. Since we need to frequently remove points from the map during downsampling process, it is quite inconvenient to delete those downsampled points, which are not longer necessary for us, from an external array or vector. 

There are many other ways to locate a point or specific area by ``ikd-Tree``. I am willing to see if I can help you on this issue.

**Comment by Woodpecker0** [comment]
> Hey @Woodpecker0 !
> 
> For the first question, yes. Please remove all the two conditions `&& !root->point_downsample_deleted` in the function `flatten`. Then DIY your own conditions in the same place and store the points you need in a global storage.
> 
> For your second question, sorry that we did not provide indices. The `ikd-Tree` is design to achieve high efficiency in both time and space. Since we need to frequently remove points from the map during downsampling process, it is quite inconvenient to delete those downsampled points, which are not longer necessary for us, from an external array or vector.
> 
> There are many other ways to locate a point or specific area by `ikd-Tree`. I am willing to see if I can help you on this issue.

Thank you ^_^
