### ISSUE TITLE
Weird phenomenon on `Delete_Point_Boxes` function

### ISSUE THREAD

**Issue by LimHyungTae** [hku-mars/ikd-Tree#14]
Dear Admin:

First, thank you for sharing your invaluable codes.

But, I'd like to use your incremental Tree algorithm to achieve radius search; unfortunately, I think the code doesn't support the radius search function.

Is there any particular issue not implementing radius search?

Thanks in advance!

**Comment by LimHyungTae** [comment]
So, I use `Delete_Point_Boxes` to substitute radius search, yet it doesn't work.

The example snippet is as follows:

<script src="https://gist.github.com/LimHyungTae/3953a4ee4cca2fcedf2167d26a41ae72.js"></script>

I'd like to extract the region highlighted by the yellow box.

![image](https://user-images.githubusercontent.com/35317311/141990515-cd7d19d2-1fc4-4fae-9a46-c253e43e8470.png)

**Comment by LimHyungTae** [comment]
Furthermore, I found that ikd tree successfully has the complement of the box region as follows:

**Codes to get complement of point cloud***
```cpp
pcl::PointCloud<PointType>::Ptr dst(new pcl::PointCloud <PointType>);

  ikd_Tree.flatten(ikd_Tree.Root_Node, ikd_Tree.PCL_Storage, NOT_RECORD);
  dst->points = ikd_Tree.PCL_Storage;
```

**Result**
![image](https://user-images.githubusercontent.com/35317311/142143009-8ad39d64-b37a-4aab-8287-44695fb324a1.png)

How can I get the deleted points successfully? It would be a great help for me and I'll upload some visualized examples of ikd-tree and send pull requests for letting other people use this super-wonderful method broadly!

**Comment by Ecstasy-EC** [comment]
@LimHyungTae 

SORRY for my late reply. 

For the radius search, it can be easily implemented on the ikd-Tree in a very similar way to the function `Search_by_range`. However, since the ikd-Tree was designed for FAST-LIO2 which did not require radius search, only range knn search is provided. I will update a new version with radius search next week to make the ikd-Tree more applicable. 

For your test result, the box delete simply attaches 'deleted' labels on the nodes, after which those deleted points are removed during a rebuilding process. In other words, the delete operation and the remove operation are not performed at the same time. This is why you saw different number of deleted points (from delete operation) and removed points (from `acquire_removed_points` function`). Please refer to our preprint paper for further details. 

If you want to obtain the deleted points, you should use `Search_by_range` function before you use box delete. This is also what I have done in the downsampling process. 

Should you have any further questions, please mention me in your issues as it will automatically send me an email to notice.

**Comment by LimHyungTae** [comment]
Dear @Ecstasy-EC , you're 100% right!! I read the paper and I've known the async. operation of ikd-tree, but I think I didn't understand what eventually means lol. As you mentioned, using `Search_by_range()` function works as I wished as follows!!!

![image](https://user-images.githubusercontent.com/35317311/143388713-3f2597bc-573f-48b9-981f-909dfedf9a8c.png)

To achieve this, I wrapped up the private function `Search_by_range()` by a new public function called `Get_Points_in_Box()` in your code format.

```
template <typename PointType>
int KD_TREE<PointType>::Get_Points_in_Box(const BoxPointType &Box_of_Point, PointVector &Storage)
{
    Storage.clear();
    Search_by_range(Root_Node, Box_of_Point, Storage);
}
```

It is super fantastic! I can't wait for the next week, i.e. updated version of ikd-tree. :heart_eyes:  Thank you!
